graphhopper:
  datareader.file: data/south-korea-251014.osm.pbf
  # for multiple files you can use: gtfs.file: file1.zip,file2.zip,file3.zip
  gtfs.file: data/202303_GTFS_DataSet.zip
  graph.location: graphs/brandenburg-with-transit

  profiles:
    - name: foot
      custom_model_files:
        - foot.json

  import.osm.ignored_highways: motorway,trunk
  graph.encoded_values: foot_access, foot_average_speed, foot_priority, foot_road_access, hike_rating, mtb_rating, country, road_class

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: localhost
  admin_connectors:
    - type: http
      port: 8990
      bind_host: localhost
